eos-updater-ctl: Drop an unnecessary user_data argument
This was causing warnings whenever signal_emitted() was called:
   TypeError: signal_emitted() takes 4 positional arguments but 5 were
   given

Signed-off-by: Philip Withnall <withnall@endlessm.com>